name: Science Bot Run

on:
  schedule:
    # اجرا در ساعت‌های ۳:۳۰، ۷:۳۰، ۱۱:۳۰، ۱۵:۳۰، ۱۹:۳۰ و ۲۳:۳۰ به وقت تهران
    # (معادل ساعت‌های جهانی: 0, 4, 8, 12, 16, 20)
    - cron: '0 0,4,8,12,16,20 * * *'
  workflow_dispatch: # این خط اجازه میده دکمه‌ی اجرای دستی داشته باشیم

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run Bot
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          ADMIN_CHAT_ID: ${{ secrets.ADMIN_CHAT_ID }}
        run: python main.py
